import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { BellRing, CheckCheck, CircleAlert, Info, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

const typeMeta = { info: { label: "Informação", icon: Info, className: "bg-blue-500/10 text-blue-700 dark:text-blue-300" }, warning: { label: "Atenção", icon: CircleAlert, className: "bg-amber-500/10 text-amber-700 dark:text-amber-300" }, critical: { label: "Crítico", icon: ShieldAlert, className: "bg-rose-500/10 text-rose-700 dark:text-rose-300" }, success: { label: "Concluído", icon: CheckCheck, className: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" } } as const;

export default function AlertsCenter() {
  const utils = trpc.useUtils(); const alerts = trpc.alerts.list.useQuery(undefined, { refetchInterval: 60_000 });
  const markRead = trpc.alerts.markRead.useMutation({ onSuccess: () => utils.alerts.list.invalidate() });
  const markAll = trpc.alerts.markAllRead.useMutation({ onSuccess: async () => { await utils.alerts.list.invalidate(); toast.success("Todos os alertas foram marcados como lidos."); } });
  const rows = alerts.data ?? []; const unread = rows.filter(alert => !alert.isRead).length;
  return <AdminLayout title="Alertas Internos"><div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><BellRing size={17} /> Central operacional</div><h1 className="text-2xl font-bold">Alertas internos</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhe tarefas críticas, avisos e eventos importantes sem depender de mensagens externas.</p></div><Button variant="outline" disabled={!unread || markAll.isPending} onClick={() => markAll.mutate()} className="gap-2"><CheckCheck size={16} /> Marcar todos como lidos</Button></div><div className="grid gap-3 sm:grid-cols-2"><Card><CardContent className="p-4"><p className="text-2xl font-bold text-primary">{unread}</p><p className="text-xs text-muted-foreground">Alerta(s) ainda não lido(s)</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-2xl font-bold">{rows.length}</p><p className="text-xs text-muted-foreground">Evento(s) recentes no painel</p></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Linha do tempo de alertas</CardTitle><CardDescription>As tarefas de manutenção de prioridade alta ou crítica entram automaticamente aqui.</CardDescription></CardHeader><CardContent className="space-y-3">{rows.map(alert => { const meta = typeMeta[alert.type]; const Icon = meta.icon; return <button key={alert.id} onClick={() => !alert.isRead && markRead.mutate({ id: alert.id })} className={`w-full rounded-xl border p-4 text-left transition hover:border-primary/50 ${alert.isRead ? "opacity-70" : "bg-primary/[.03]"}`}><div className="flex gap-3"><div className={`mt-0.5 rounded-md p-2 ${meta.className}`}><Icon size={16} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{alert.title}</p><Badge variant="secondary" className={meta.className}>{meta.label}</Badge>{!alert.isRead && <Badge>Não lido</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{alert.content}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(alert.createdAt).toLocaleString("pt-BR")}</p></div></div></button>; })}{!alerts.isLoading && !rows.length && <div className="py-12 text-center text-sm text-muted-foreground"><BellRing className="mx-auto mb-2 opacity-40" size={28} /> Nenhum alerta interno por enquanto.</div>}</CardContent></Card></div></AdminLayout>;
}
