import { CheckSquare, CircleHelp, Download, RefreshCw, Send, Smartphone, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";
import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function ApkUpdates() {
  const query = trpc.apkUpdates.list.useQuery();
  const [selected, setSelected] = useState<number[]>([]);
  const data = query.data ?? { versions: { ouroPro: null, maximus: null }, devices: [] };
  const outdated = data.devices.filter((device) => device.outdated);
  const unknown = data.devices.filter((device) => !device.appVersion);
  const selectedDevices = useMemo(() => data.devices.filter((device) => selected.includes(device.id) && device.waUrl), [data.devices, selected]);
  const toggle = (id: number) => setSelected((old) => old.includes(id) ? old.filter((value) => value !== id) : [...old, id]);
  const prepareMessages = () => { if (!selectedDevices.length) return toast.error("Selecione clientes desatualizados com telefone cadastrado."); selectedDevices.forEach((device, index) => window.setTimeout(() => window.open(device.waUrl!, "_blank", "noopener,noreferrer"), index * 450)); toast.success(`${selectedDevices.length} conversa(s) preparada(s).`); };
  return <AdminLayout title="Atualizações do APK"><div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><Download size={17} /> Gestão de versões</div><h1 className="text-2xl font-bold">Atualizações do APK</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhe as versões reportadas pelos aplicativos e avise quem precisa atualizar.</p></div><Button className="gap-2 text-black dark:text-white" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw size={16} className={query.isFetching ? "animate-spin" : ""} /> Atualizar</Button></div>
    <div className="grid gap-3 sm:grid-cols-4"><Metric icon={<Smartphone size={18} />} value={data.devices.length} label="Dispositivos" /><Metric icon={<TriangleAlert size={18} />} value={outdated.length} label="Desatualizados" tone="text-destructive" /><Metric icon={<CircleHelp size={18} />} value={unknown.length} label="Versão não informada" tone="text-amber-600" /><Metric icon={<Download size={18} />} value={data.versions.ouroPro || "—"} label="OuroPro mais recente" /></div>
    <Card><CardHeader className="gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="text-base">Versões por cliente</CardTitle><CardDescription>Versões mais recentes: OuroPro {data.versions.ouroPro || "não configurada"} · Maximus {data.versions.maximus || "não configurada"}.</CardDescription></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setSelected(outdated.filter((device) => device.waUrl).map((device) => device.id))} className="gap-1.5"><CheckSquare size={15} /> Selecionar desatualizados</Button><Button size="sm" onClick={prepareMessages} className="gap-1.5 text-black dark:text-white"><Send size={15} /> Avisar ({selectedDevices.length})</Button></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-y bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="w-12 px-5 py-3"></th><th className="px-5 py-3">Cliente</th><th className="px-5 py-3">Aplicativo</th><th className="px-5 py-3">Versão instalada</th><th className="px-5 py-3">Versão atual</th><th className="px-5 py-3">Situação</th></tr></thead><tbody>{data.devices.map((device) => <tr key={device.id} className="border-b last:border-0"><td className="px-5 py-4"><Checkbox checked={selected.includes(device.id)} disabled={!device.waUrl} onCheckedChange={() => toggle(device.id)} /></td><td className="px-5 py-4"><p className="font-medium">{device.nomeServer}</p><p className="text-xs text-muted-foreground">{device.telefone || "Sem telefone"}</p></td><td className="px-5 py-4">{device.app || "Não informado"}</td><td className="px-5 py-4">{device.appVersion || <span className="text-muted-foreground">Não informada</span>}</td><td className="px-5 py-4">{device.latestVersion || <span className="text-muted-foreground">Não configurada</span>}</td><td className="px-5 py-4">{device.outdated ? <Badge variant="destructive">Atualizar</Badge> : device.appVersion ? <Badge variant="secondary">Atualizado</Badge> : <Badge className="bg-amber-500 text-black hover:bg-amber-500">Aguardando versão</Badge>}</td></tr>)}{!query.isLoading && !data.devices.length && <tr><td colSpan={6} className="px-5 py-14 text-center text-muted-foreground">Nenhum dispositivo cadastrado.</td></tr>}</tbody></table></div></CardContent></Card>
  </div></AdminLayout>;
}
function Metric({ icon, value, label, tone = "text-primary" }: { icon: React.ReactNode; value: string | number; label: string; tone?: string }) { return <Card><CardContent className="p-4"><div className={`mb-2 ${tone}`}>{icon}</div><p className={`text-2xl font-bold ${tone}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
