import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, CheckCircle2, CircleAlert, Clock3, ExternalLink, ListChecks, Loader2, Radio, RefreshCw, ServerCrash, ShieldCheck, ShieldOff, Zap, Wifi } from "lucide-react";
import { toast } from "sonner";

function checkedLabel(value: Date | string | null | undefined) {
  if (!value) return "Ainda não verificada";
  const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000));
  if (minutes < 1) return "Agora";
  if (minutes < 60) return `Há ${minutes} min`;
  return `Há ${Math.floor(minutes / 60)} h`;
}

export default function ListMonitor() {
  const utils = trpc.useUtils();
  const query = trpc.listMonitor.list.useQuery();
  const failover = trpc.listFailover.overview.useQuery();
  const instability = trpc.listMonitor.instabilityReport.useQuery();
  const macTests = trpc.listMonitor.testMacs.useQuery(undefined, { enabled: false });
  const check = trpc.listMonitor.check.useMutation({ onSuccess: async () => { await Promise.all([utils.listMonitor.list.invalidate(), utils.superPanel.overview.invalidate()]); } });
  const checkAll = trpc.listMonitor.checkAll.useMutation({ onSuccess: async (result) => { await Promise.all([utils.listMonitor.list.invalidate(), utils.superPanel.overview.invalidate()]); toast.success(`${result.checked} lista(s) verificadas: ${result.success} disponível(is) e ${result.errors} com erro.`); } });
  const runFailover = trpc.listFailover.runNow.useMutation({ onSuccess: async (result) => { await Promise.all([utils.listFailover.overview.invalidate(), utils.listMonitor.list.invalidate()]); toast.success(`${result.checked} teste(s) executados; ${result.switched} troca(s) automática(s).`); }, onError: error => toast.error(error.message) });
  const enableFailover = trpc.listFailover.enable.useMutation({ onSuccess: async () => { await utils.listFailover.overview.invalidate(); toast.success("Troca automática ativada a cada 10 minutos."); }, onError: error => toast.error(error.message) });
  const disableFailover = trpc.listFailover.disable.useMutation({ onSuccess: async () => { await utils.listFailover.overview.invalidate(); toast.success("Troca automática desativada."); }, onError: error => toast.error(error.message) });
  const lists = query.data ?? [];
  const summary = lists.reduce((acc, item) => { const status = (item.lastCheck?.status ?? "pending") as "success" | "error" | "pending"; acc[status] += 1; return acc; }, { success: 0, error: 0, pending: 0 });
  const enabled = Boolean(failover.data?.setting?.enabled);

  return <AdminLayout title="Monitor de Listas"><div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><Activity size={17} /> Super Painel</div><h1 className="text-2xl font-bold">Monitor de Listas</h1><p className="mt-1 text-sm text-muted-foreground">Monitore a disponibilidade das listas e mantenha um caminho de reserva para cada cliente.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { query.refetch(); failover.refetch(); }} className="gap-2"><RefreshCw size={16} className={query.isFetching ? "animate-spin" : ""} /> Atualizar</Button><Button variant="outline" onClick={() => macTests.refetch()} className="gap-2"><Wifi size={16} /> Testar MACs</Button><Button onClick={() => checkAll.mutate()} disabled={checkAll.isPending || lists.length === 0} className="gap-2 text-black dark:text-white">{checkAll.isPending ? <Loader2 size={16} className="animate-spin" /> : <ListChecks size={16} />} Verificar todas</Button></div></div>

    <Card className={enabled ? "border-emerald-500/30 bg-emerald-500/5" : "border-amber-500/30 bg-amber-500/5"}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 font-semibold"><Zap size={17} className="text-primary" /> Troca automática de listas</p><p className="mt-1 text-sm text-muted-foreground">{enabled ? "Ativa: a cada 10 minutos, troca Lista 1 → Lista 2 → Lista 3 quando a atual falha." : "Desativada: ative para o painel priorizar a próxima lista que estiver funcionando."}</p></div><div className="flex flex-wrap gap-2">{enabled ? <Button variant="outline" className="gap-2" disabled={disableFailover.isPending} onClick={() => disableFailover.mutate()}><ShieldOff size={16} /> Desativar</Button> : <Button className="gap-2 text-black dark:text-white" disabled={enableFailover.isPending} onClick={() => enableFailover.mutate()}><ShieldCheck size={16} /> Ativar a cada 10 min</Button>}<Button variant="outline" className="gap-2" disabled={runFailover.isPending} onClick={() => runFailover.mutate()}>{runFailover.isPending ? <Loader2 size={16} className="animate-spin" /> : <Zap size={16} />} Testar agora</Button></div></CardContent></Card>

    <Card className="border-blue-200 bg-blue-50/60 dark:border-blue-900 dark:bg-blue-950/20"><CardContent className="p-4 text-sm text-blue-800 dark:text-blue-200">A verificação usa somente URLs públicas HTTP/HTTPS. Endereços locais e internos são bloqueados por segurança.</CardContent></Card>
    <div className="grid grid-cols-3 gap-3"><Metric value={summary.success} label="Disponíveis" className="text-emerald-600" /><Metric value={summary.error} label="Com erro" className="text-rose-600" /><Metric value={summary.pending} label="Não verificadas" className="text-slate-500" /></div>
    {macTests.data && <Card><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="flex items-center gap-2 font-semibold"><Wifi size={17} className="text-primary" /> Teste em massa de MACs</p><p className="mt-1 text-sm text-muted-foreground">Usa o último heartbeat de cada aplicativo para indicar conexão nos últimos 15 minutos.</p></div><div className="flex gap-4 text-sm"><span className="font-medium text-emerald-600">{macTests.data.online} online</span><span className="font-medium text-rose-600">{macTests.data.offline} offline</span><span className="text-muted-foreground">{macTests.data.checked} testados</span></div></CardContent></Card>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Radio size={17} /> Listas cadastradas</CardTitle><CardDescription>O botão individual verifica apenas a lista escolhida.</CardDescription></CardHeader><CardContent><div className="space-y-3">{lists.map(item => { const result = item.lastCheck; const ok = result?.status === "success"; const failed = result?.status === "error"; return <div key={`${item.deviceId}:${item.deviceUrlId ?? "main"}`} className="flex flex-col gap-4 rounded-xl border p-4 xl:flex-row xl:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate font-medium">{item.listName}</p>{ok && <CheckCircle2 size={16} className="shrink-0 text-emerald-600" />}{failed && <ServerCrash size={16} className="shrink-0 text-rose-600" />}</div><p className="truncate text-sm text-muted-foreground">{item.deviceName}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.url}</p></div><div className="min-w-36"><p className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 size={13} /> Última verificação</p><p className="text-sm">{checkedLabel(result?.checkedAt)}</p></div><div className="min-w-44"><p className="text-xs text-muted-foreground">Resultado</p>{result ? <Badge variant="secondary" className={ok ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-rose-500/10 text-rose-700 dark:text-rose-300"}>{result.message}{result.responseTimeMs ? ` · ${result.responseTimeMs}ms` : ""}</Badge> : <Badge variant="secondary">Pendente</Badge>}</div><div className="flex gap-2"><Button size="sm" onClick={() => check.mutate({ deviceId: item.deviceId, deviceUrlId: item.deviceUrlId })} disabled={check.isPending} className="gap-1.5 text-black dark:text-white">{check.isPending ? <Loader2 size={14} className="animate-spin" /> : <Activity size={14} />} Verificar</Button><a href={item.url} target="_blank" rel="noreferrer"><Button size="sm" variant="outline"><ExternalLink size={14} /></Button></a></div></div>; })}{!query.isLoading && lists.length === 0 && <div className="py-12 text-center text-sm text-muted-foreground"><CircleAlert className="mx-auto mb-2 opacity-40" size={28} /> Nenhuma lista com URL disponível foi encontrada.</div>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Relatório de instabilidade</CardTitle><CardDescription>Listas e servidores com maior taxa de falha nas últimas verificações.</CardDescription></CardHeader><CardContent className="space-y-2">{instability.data?.slice(0, 10).map(item => <div key={item.url} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><div className="min-w-0"><p className="truncate font-medium">{item.url}</p><p className="text-xs text-muted-foreground">{item.checks} verificações · {item.errors} falhas{item.avgResponseMs ? ` · ${item.avgResponseMs}ms` : ""}</p></div><Badge variant={item.errorRate >= 50 ? "destructive" : "secondary"}>{item.errorRate}% com erro</Badge></div>)}{!instability.data?.length && <p className="py-4 text-center text-sm text-muted-foreground">Ainda não há verificações suficientes para o relatório.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Histórico de trocas automáticas</CardTitle><CardDescription>Registra quando uma lista falha e o painel prioriza a próxima lista disponível.</CardDescription></CardHeader><CardContent className="space-y-2">{failover.data?.events.map(event => <div key={event.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">Cliente #{event.deviceId}</p><p className="mt-1 text-muted-foreground">{event.reason}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString("pt-BR")}</p></div>)}{!failover.data?.events.length && <p className="py-4 text-center text-sm text-muted-foreground">Nenhuma troca automática registrada.</p>}</CardContent></Card>
  </div></AdminLayout>;
}

function Metric({ value, label, className }: { value: number; label: string; className: string }) { return <Card><CardContent className="p-4"><p className={`text-2xl font-bold ${className}`}>{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
