import { Link } from "wouter";
import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, CheckCircle2, CircleOff, ClipboardList, ListX, Loader2, Plus, RefreshCw, ShieldAlert, Wrench } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const priorityLabel = { low: "Baixa", medium: "Média", high: "Alta", critical: "Crítica" } as const;
const priorityClass = { low: "bg-slate-500/10 text-slate-700 dark:text-slate-300", medium: "bg-blue-500/10 text-blue-700 dark:text-blue-300", high: "bg-amber-500/10 text-amber-700 dark:text-amber-300", critical: "bg-rose-500/10 text-rose-700 dark:text-rose-300" } as const;
const statusLabel = { open: "Aberta", in_progress: "Em andamento", resolved: "Resolvida", cancelled: "Cancelada" } as const;

export default function MaintenanceCenter() {
  const [showForm, setShowForm] = useState(false); const [deviceId, setDeviceId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [priority, setPriority] = useState<keyof typeof priorityLabel>("medium"); const [dueAt, setDueAt] = useState("");
  const utils = trpc.useUtils(); const query = trpc.maintenance.overview.useQuery(undefined, { refetchInterval: 60_000 }); const tasks = trpc.maintenance.tasks.list.useQuery(); const devices = trpc.devices.list.useQuery({ page: 1, pageSize: 100 }); const data = query.data ?? { listErrors: 0, offline: 0, blocked: 0, actions: [] };
  const create = trpc.maintenance.tasks.create.useMutation({ onSuccess: async () => { await utils.maintenance.tasks.list.invalidate(); toast.success("Tarefa de manutenção criada."); setShowForm(false); setDeviceId(""); setTitle(""); setDescription(""); setPriority("medium"); setDueAt(""); }, onError: (error) => toast.error(error.message) });
  const update = trpc.maintenance.tasks.update.useMutation({ onSuccess: async () => { await utils.maintenance.tasks.list.invalidate(); toast.success("Tarefa atualizada."); }, onError: (error) => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim().length < 3) return toast.error("Informe uma tarefa com pelo menos 3 caracteres."); create.mutate({ deviceId: deviceId ? Number(deviceId) : undefined, title, description: description || undefined, priority, dueAt: dueAt || undefined }); };
  return <AdminLayout title="Central de Manutenção"><div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><Wrench size={17} /> Operação preventiva</div><h1 className="text-2xl font-bold">Central de Manutenção</h1><p className="mt-1 text-sm text-muted-foreground">Priorize falhas e acompanhe cada tarefa até a solução.</p></div><div className="flex gap-2"><Button variant="outline" className="gap-2" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw size={16} className={query.isFetching ? "animate-spin" : ""} /> Atualizar</Button><Button className="gap-2 text-black dark:text-white" onClick={() => setShowForm(value => !value)}><Plus size={16} /> Nova tarefa</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric icon={<ListX size={18} />} value={data.listErrors} label="Listas com falha" className="text-destructive" /><Metric icon={<CircleOff size={18} />} value={data.offline} label="Offline há 24h" className="text-amber-600" /><Metric icon={<ShieldAlert size={18} />} value={data.blocked} label="Bloqueados / expirados" className="text-primary" /></div>
    {showForm && <Card className="border-primary/30"><CardHeader><CardTitle className="text-base">Criar tarefa operacional</CardTitle><CardDescription>A tarefa fica atribuída a você por padrão e aparece na fila até ser resolvida.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1.5 text-sm font-medium lg:col-span-2">Título<Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Ex.: Verificar lista que parou de funcionar" /></label><label className="grid gap-1.5 text-sm font-medium">Cliente <select value={deviceId} onChange={event => setDeviceId(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Sem cliente específico</option>{devices.data?.data.map(device => <option key={device.id} value={device.id}>{device.nomeServer} · {device.mac}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Prioridade <select value={priority} onChange={event => setPriority(event.target.value as keyof typeof priorityLabel)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{Object.entries(priorityLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium lg:col-span-3">Detalhes <Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Descreva o problema, testes já realizados e próximo passo." /></label><label className="grid gap-1.5 text-sm font-medium">Prazo <Input type="date" value={dueAt} onChange={event => setDueAt(event.target.value)} /></label><div className="lg:col-span-4"><Button type="submit" disabled={create.isPending} className="gap-2 text-black dark:text-white">{create.isPending && <Loader2 size={15} className="animate-spin" />} Criar tarefa</Button></div></form></CardContent></Card>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ClipboardList size={18} /> Fila de manutenção</CardTitle><CardDescription>Defina prioridade e avance cada tarefa até a conclusão.</CardDescription></CardHeader><CardContent className="space-y-3">{tasks.data?.map(task => <div key={task.id} className="flex flex-col gap-3 rounded-xl border p-4 xl:flex-row xl:items-center"><Badge className={`${priorityClass[task.priority]} w-fit`}>{priorityLabel[task.priority]}</Badge><div className="min-w-0 flex-1"><p className="font-medium">{task.title}</p><p className="mt-1 text-sm text-muted-foreground">{task.description || "Sem detalhes adicionais."}</p><p className="mt-1 text-xs text-muted-foreground">Responsável: você{task.deviceName ? ` · Cliente: ${task.deviceName}` : ""}{task.dueAt ? ` · Prazo: ${new Date(task.dueAt).toLocaleDateString("pt-BR", { timeZone: "UTC" })}` : ""}</p></div><select value={task.status} onChange={event => update.mutate({ id: task.id, status: event.target.value as keyof typeof statusLabel })} className="h-9 rounded-md border border-input bg-background px-2 text-sm" disabled={update.isPending}>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>)}{!tasks.isLoading && !(tasks.data?.length) && <div className="py-10 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 opacity-50" size={26} /> Nenhuma tarefa cadastrada na fila.</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle size={18} /> Ações detectadas automaticamente</CardTitle><CardDescription>Alertas técnicos que podem virar tarefas na fila acima.</CardDescription></CardHeader><CardContent><div className="space-y-3">{data.actions.map(action => <div key={action.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-medium">{action.type}</p><p className="mt-1 text-sm text-muted-foreground">{action.message}</p></div>{action.type === "Lista indisponível" ? <Link href="/monitor-listas"><Button variant="outline" size="sm" className="gap-1.5">Monitor de Listas <ArrowRight size={14} /></Button></Link> : <Link href="/sessoes"><Button variant="outline" size="sm" className="gap-1.5">Ver sessões <ArrowRight size={14} /></Button></Link>}</div>)}{!query.isLoading && data.actions.length === 0 && <div className="flex flex-col items-center gap-2 py-8 text-center"><CheckCircle2 className="text-emerald-600" size={28} /><p className="font-medium">Nenhuma ação urgente no momento</p></div>}</div></CardContent></Card>
  </div></AdminLayout>;
}
function Metric({ icon, value, label, className }: { icon: React.ReactNode; value: number; label: string; className: string }) { return <Card><CardContent className="p-4"><div className={`mb-2 ${className}`}>{icon}</div><p className={`text-2xl font-bold ${className}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
