import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { formatDateOnlyPtBr } from "@shared/dateOnly";
import { CheckCircle2, CircleDollarSign, Loader2, Plus, ReceiptText, Repeat2, Trash2, WalletCards } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
type Filter = "all" | "paid" | "pending" | "overdue";

export default function ResellerBilling() {
  const [showForm, setShowForm] = useState(false); const [filter, setFilter] = useState<Filter>("all"); const [resellerId, setResellerId] = useState(""); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState(""); const [recurrenceMonths, setRecurrenceMonths] = useState("1"); const [note, setNote] = useState("");
  const utils = trpc.useUtils(); const billing = trpc.resellerBilling.list.useQuery(); const resellers = trpc.revendas.list.useQuery({ page: 1, pageSize: 100 });
  const create = trpc.resellerBilling.create.useMutation({ onSuccess: async () => { await utils.resellerBilling.list.invalidate(); toast.success("Cobrança de revenda criada."); setShowForm(false); setResellerId(""); setAmount(""); setDueDate(""); setRecurrenceMonths("1"); setNote(""); }, onError: (error) => toast.error(error.message) });
  const markPaid = trpc.resellerBilling.markPaid.useMutation({ onSuccess: async (data) => { await utils.resellerBilling.list.invalidate(); toast.success(data.nextBillingId ? "Pagamento confirmado e próxima cobrança criada." : "Pagamento confirmado."); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.resellerBilling.remove.useMutation({ onSuccess: async () => { await utils.resellerBilling.list.invalidate(); toast.success("Cobrança removida."); }, onError: (error) => toast.error(error.message) });
  const rows = billing.data ?? []; const filtered = rows.filter(row => filter === "all" || row.effectiveStatus === filter); const totals = useMemo(() => rows.reduce((acc, row) => { const value = Number(row.amount); if (row.effectiveStatus === "paid") acc.paid += value; else if (row.effectiveStatus === "overdue") acc.overdue += value; else acc.pending += value; return acc; }, { paid: 0, pending: 0, overdue: 0 }), [rows]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!resellerId || !amount || !dueDate) return toast.error("Selecione a revenda, informe valor e vencimento."); create.mutate({ resellerId: Number(resellerId), amount: amount.replace(",", "."), dueDate, recurrenceMonths: Number(recurrenceMonths), note: note || undefined }); };
  const status = { paid: { label: "Pago", tone: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" }, pending: { label: "Pendente", tone: "bg-amber-500/10 text-amber-700 dark:text-amber-300" }, overdue: { label: "Atrasado", tone: "bg-rose-500/10 text-rose-700 dark:text-rose-300" } } as const;
  return <AdminLayout title="Cobranças de Revendas"><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-primary mb-1"><WalletCards size={19} /><span className="text-xs font-bold uppercase tracking-[.18em]">Super Painel</span></div><h1 className="text-2xl font-bold">Cobranças de Revendas</h1><p className="text-sm text-muted-foreground mt-1">Controle mensalidades das revendas e gere a próxima cobrança ao confirmar o pagamento.</p></div><Button onClick={() => setShowForm(value => !value)} className="gap-2 self-start sm:self-auto text-black dark:text-white"><Plus size={16} /> Nova cobrança</Button></div>
    <div className="grid grid-cols-3 gap-3"><Metric label="Recebido" value={totals.paid} tone="text-emerald-600" /><Metric label="Pendente" value={totals.pending} tone="text-amber-600" /><Metric label="Em atraso" value={totals.overdue} tone="text-rose-600" /></div>
    {showForm && <Card className="border-primary/30"><CardHeader><CardTitle className="text-base">Nova cobrança recorrente</CardTitle><CardDescription>Ao confirmar o pagamento, o painel cria automaticamente a próxima cobrança conforme a periodicidade escolhida.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1.5 text-sm font-medium lg:col-span-2">Revenda<select value={resellerId} onChange={event => setResellerId(event.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione a revenda</option>{resellers.data?.data.map(item => <option key={item.id} value={item.id}>{item.name || item.email} · limite {item.limiteDevices}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Valor<Input inputMode="decimal" placeholder="Ex: 50,00" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="grid gap-1.5 text-sm font-medium">Vencimento<Input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></label><label className="grid gap-1.5 text-sm font-medium">Recorrência<select value={recurrenceMonths} onChange={event => setRecurrenceMonths(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="1">Mensal</option><option value="3">Trimestral</option><option value="6">Semestral</option><option value="12">Anual</option><option value="0">Sem recorrência</option></select></label><label className="grid gap-1.5 text-sm font-medium lg:col-span-2">Observação<Input placeholder="Ex: Mensalidade de agosto" value={note} onChange={event => setNote(event.target.value)} /></label><div className="flex items-end"><Button type="submit" disabled={create.isPending} className="w-full gap-2 text-black dark:text-white">{create.isPending && <Loader2 size={15} className="animate-spin" />}Salvar cobrança</Button></div></form></CardContent></Card>}
    <Card><CardHeader className="gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><ReceiptText size={17} /> Histórico de cobranças</CardTitle><CardDescription>{rows.length} registro(s) de cobrança de revenda.</CardDescription></div><div className="flex flex-wrap gap-2">{(["all", "pending", "paid", "overdue"] as const).map(value => <Button key={value} size="sm" variant={filter === value ? "default" : "outline"} onClick={() => setFilter(value)}>{value === "all" ? "Todos" : status[value].label}</Button>)}</div></div></CardHeader><CardContent><div className="space-y-3">{filtered.map(row => { const item = status[row.effectiveStatus as keyof typeof status]; return <div key={row.id} className="flex flex-col gap-4 rounded-xl border p-4 xl:flex-row xl:items-center"><div className="flex-1 min-w-0"><p className="font-medium truncate">{row.resellerName || row.resellerEmail || `Revenda #${row.resellerId}`}</p><p className="text-xs text-muted-foreground truncate">{row.resellerEmail}</p>{row.note && <p className="mt-1 text-sm text-muted-foreground">{row.note}</p>}</div><p className="text-lg font-bold">{currency.format(Number(row.amount))}</p><Badge variant="secondary" className={`${item.tone} w-fit`}>{item.label}</Badge><div className="min-w-28 text-sm"><p className="text-xs text-muted-foreground">Vencimento</p><p>{formatDateOnlyPtBr(row.dueDate)}</p></div><div className="min-w-28 text-sm"><p className="text-xs text-muted-foreground">Recorrência</p><p className="flex items-center gap-1">{row.recurrenceMonths > 0 ? <><Repeat2 size={13} /> {row.recurrenceMonths} mês(es)</> : "Única"}</p></div><div className="flex gap-2">{row.effectiveStatus !== "paid" && <Button size="sm" disabled={markPaid.isPending} onClick={() => markPaid.mutate({ id: row.id })} className="gap-1.5 text-black dark:text-white"><CheckCircle2 size={14} /> Pago</Button>}<Button size="sm" variant="outline" disabled={remove.isPending} onClick={() => { if (window.confirm("Remover esta cobrança?")) remove.mutate({ id: row.id }); }}><Trash2 size={14} /></Button></div></div>; })}{!billing.isLoading && filtered.length === 0 && <div className="py-12 text-center text-sm text-muted-foreground"><CircleDollarSign size={28} className="mx-auto mb-2 opacity-40" /> Nenhuma cobrança neste filtro.</div>}</div></CardContent></Card>
  </div></AdminLayout>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <Card><CardContent className="p-4"><p className={`text-lg font-bold sm:text-2xl ${tone}`}>{currency.format(value)}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
