import { Activity, BarChart3, CreditCard, Download, Layers3, RefreshCw, ShieldAlert, Trophy, UsersRound } from "lucide-react";
import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { downloadCsv } from "@/lib/csv";
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("pt-BR", { timeZone: "UTC" }) : "Sem validade";
export default function ResellerReport() {
  const query = trpc.resellerReport.list.useQuery();
  const rows = query.data ?? [];
  const totals = rows.reduce((sum, row) => ({ clients: sum.clients + row.clientCount, activated: sum.activated + row.apkActivatedClients, online: sum.online + row.onlineClients, received: sum.received + row.finance.received, pending: sum.pending + row.finance.pending, expiring: sum.expiring + row.expiringSoon }), { clients: 0, activated: 0, online: 0, received: 0, pending: 0, expiring: 0 });
  const ranking = [...rows].sort((a, b) => b.apkActivatedClients - a.apkActivatedClients || b.clientCount - a.clientCount || (a.name || "").localeCompare(b.name || "", "pt-BR"));
  const exportReport = () => downloadCsv("relatorio-revendas.csv", ["Posição", "Revenda", "E-mail", "Clientes", "APKs ativados", "Online agora", "Apps", "Limite", "Restante", "Vencem em 7 dias", "Recebido", "Pendente", "Atrasado", "Status"], ranking.map((row, index) => [index + 1, row.name, row.email, row.clientCount, row.apkActivatedClients, row.onlineClients, row.appBreakdown.map((item) => `${item.app}: ${item.activated}/${item.clients}`).join(" | "), row.limiteDevices, row.remainingDevices, row.expiringSoon, row.finance.received, row.finance.pending, row.finance.overdue, row.isActive ? "Ativa" : "Bloqueada"]));
  return <AdminLayout title="Relatório de Revendas"><div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><BarChart3 size={17} /> Visão do proprietário</div><h1 className="text-2xl font-bold">Relatório de Revendas</h1><p className="mt-1 text-sm text-muted-foreground">Controle de clientes, APKs ativados por heartbeat e desempenho de cada revenda.</p></div><div className="flex gap-2"><Button variant="outline" className="gap-2" onClick={exportReport}><Download size={16} /> CSV</Button><Button className="gap-2 text-black dark:text-white" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw size={16} className={query.isFetching ? "animate-spin" : ""} /> Atualizar</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<UsersRound size={18} />} label="Clientes em revendas" value={totals.clients} /><Metric icon={<Download size={18} />} label="APKs ativados" value={totals.activated} /><Metric icon={<Activity size={18} />} label="Online agora" value={totals.online} /><Metric icon={<CreditCard size={18} />} label="Recebido" value={money(totals.received)} /><Metric icon={<ShieldAlert size={18} />} label="Vencem em 7 dias" value={totals.expiring} /></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Trophy size={17} /> Ranking e desempenho por revenda</CardTitle><CardDescription>"APK ativado" significa que o dispositivo cadastrado enviou pelo menos um heartbeat. Não conta clique como download.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-sm"><thead className="border-y bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">#</th><th className="px-5 py-3">Revenda</th><th className="px-5 py-3">Clientes</th><th className="px-5 py-3">APKs</th><th className="px-5 py-3">Apps</th><th className="px-5 py-3">Limite</th><th className="px-5 py-3">Vencimentos</th><th className="px-5 py-3">Financeiro</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{ranking.map((row, index) => <tr key={row.id} className="border-b last:border-0"><td className="px-5 py-4 font-semibold text-primary">{index + 1}</td><td className="px-5 py-4"><p className="font-medium">{row.name || "Sem nome"}</p><p className="text-xs text-muted-foreground">{row.email || "Sem e-mail"} · Validade: {date(row.planValidade)}</p></td><td className="px-5 py-4"><strong>{row.clientCount}</strong><span className="ml-1 text-xs text-muted-foreground">({row.activeClients} liberados)</span></td><td className="px-5 py-4"><strong>{row.apkActivatedClients}</strong><p className="text-xs text-muted-foreground">{row.onlineClients} online agora</p></td><td className="px-5 py-4"><div className="flex max-w-64 flex-wrap gap-1">{row.appBreakdown.length ? row.appBreakdown.map((item) => <Badge key={item.app} variant="secondary">{item.app}: {item.activated}/{item.clients}</Badge>) : <span className="text-xs text-muted-foreground">Sem clientes</span>}</div></td><td className="px-5 py-4">{row.clientCount} / {row.limiteDevices ?? 0}<p className="text-xs text-muted-foreground">Restam {row.remainingDevices}</p></td><td className="px-5 py-4"><Badge variant={row.expiringSoon ? "destructive" : "secondary"}>{row.expiringSoon} próximos</Badge></td><td className="px-5 py-4"><p className="font-medium text-emerald-600">{money(row.finance.received)}</p><p className="text-xs text-muted-foreground">Pendente: {money(row.finance.pending)}</p></td><td className="px-5 py-4"><Badge variant={row.isActive ? "default" : "destructive"}>{row.isActive ? "Ativa" : "Bloqueada"}</Badge></td></tr>)}{!query.isLoading && rows.length === 0 && <tr><td colSpan={9} className="px-5 py-14 text-center text-muted-foreground">Nenhuma revenda cadastrada.</td></tr>}</tbody></table></div></CardContent></Card>
  </div></AdminLayout>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <Card><CardContent className="p-4"><div className="mb-2 text-primary">{icon}</div><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
