import AdminLayout from "@/components/AdminLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Clock3, History, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, UserCheck, UsersRound } from "lucide-react";

function relativeTime(value: Date | string | null) { if (!value) return "sem registro"; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000)); if (minutes < 1) return "agora"; if (minutes < 60) return `há ${minutes} min`; const hours = Math.floor(minutes / 60); return hours < 24 ? `há ${hours} h` : `há ${Math.floor(hours / 24)} d`; }

export default function SecurityCenter() {
  const overview = trpc.security.overview.useQuery(undefined, { refetchInterval: 60_000 });
  const data = overview.data;
  const cards = [
    { label: "Revendas monitoradas", value: data?.counts.accounts ?? 0, icon: UsersRound, tone: "text-blue-600 bg-blue-500/10" },
    { label: "Bloqueadas", value: data?.counts.blocked ?? 0, icon: LockKeyhole, tone: "text-rose-600 bg-rose-500/10" },
    { label: "Acessos em 7 dias", value: data?.counts.recentLogins ?? 0, icon: UserCheck, tone: "text-emerald-600 bg-emerald-500/10" },
    { label: "Sem acesso há 30 dias", value: data?.counts.staleAccounts ?? 0, icon: Clock3, tone: "text-amber-600 bg-amber-500/10" },
  ];
  return <AdminLayout title="Segurança"><div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-primary mb-1"><ShieldCheck size={19} /><span className="text-xs font-bold uppercase tracking-[.18em]">Super Painel</span></div><h1 className="text-2xl font-bold">Central de Segurança</h1><p className="text-sm text-muted-foreground mt-1">Acompanhe acessos, bloqueios e alterações sensíveis das suas revendas.</p></div><Button variant="outline" onClick={() => overview.refetch()} disabled={overview.isFetching} className="gap-2 self-start sm:self-auto"><RefreshCw size={16} className={overview.isFetching ? "animate-spin" : ""} /> Atualizar agora</Button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{cards.map(({ label, value, icon: Icon, tone }) => <Card key={label}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><p className="text-2xl font-bold tabular-nums">{value}</p><p className="text-xs text-muted-foreground mt-1 leading-tight">{label}</p></div><div className={`p-2 rounded-lg ${tone}`}><Icon size={18} /></div></div></CardContent></Card>)}</div>
    <div className="grid gap-5 lg:grid-cols-5"><Card className="lg:col-span-3"><CardHeader className="pb-3"><CardTitle className="flex gap-2 items-center text-base"><AlertTriangle size={17} className="text-amber-500" /> Contas que exigem atenção</CardTitle><CardDescription>Revendas bloqueadas ou sem atividade recente.</CardDescription></CardHeader><CardContent className="space-y-3">{(data?.blocked.length ?? 0) > 0 && <section className="rounded-lg border border-rose-200 bg-rose-50/60 p-3 dark:border-rose-900 dark:bg-rose-950/20"><p className="text-sm font-medium text-rose-800 dark:text-rose-200">Revendas bloqueadas</p><div className="mt-2 space-y-2">{data?.blocked.slice(0, 8).map(item => <div key={item.id} className="flex justify-between gap-3 text-sm"><span className="truncate">{item.name || item.email}</span><Badge variant="destructive">Bloqueada</Badge></div>)}</div></section>}{(data?.staleAccounts.length ?? 0) > 0 && <section className="rounded-lg border border-amber-200 bg-amber-50/60 p-3 dark:border-amber-900 dark:bg-amber-950/20"><p className="text-sm font-medium text-amber-800 dark:text-amber-200">Sem acesso há mais de 30 dias</p><div className="mt-2 space-y-2">{data?.staleAccounts.slice(0, 8).map(item => <div key={item.id} className="flex justify-between gap-3 text-sm"><span className="truncate">{item.name || item.email}</span><span className="shrink-0 text-muted-foreground">{relativeTime(item.lastSignedIn)}</span></div>)}</div></section>}{!overview.isLoading && !data?.counts.blocked && !data?.counts.staleAccounts && <div className="py-10 text-center text-sm text-muted-foreground"><ShieldCheck size={26} className="mx-auto mb-2 opacity-50" /> Nenhuma conta requer atenção agora.</div>}</CardContent></Card>
      <Card className="lg:col-span-2"><CardHeader className="pb-3"><CardTitle className="flex gap-2 items-center text-base"><History size={17} /> Eventos sensíveis</CardTitle><CardDescription>Senhas, bloqueios e alterações de revendas.</CardDescription></CardHeader><CardContent>{(data?.sensitiveActions.length ?? 0) === 0 ? <div className="py-8 text-center text-sm text-muted-foreground"><KeyRound size={22} className="mx-auto mb-2 opacity-40" /> Nenhum evento sensível registrado.</div> : <div className="space-y-4">{data?.sensitiveActions.slice(0, 12).map(event => <div key={event.id} className="border-l border-border pl-3"><p className="text-sm font-medium leading-snug">{event.summary}</p><p className="mt-1 text-xs text-muted-foreground">{relativeTime(event.createdAt)} · {event.action}</p></div>)}</div>}</CardContent></Card></div>
  </div></AdminLayout>;
}
